services:
  microservice-discovery-server:
    build: ./discovery-server
    container_name: microservice-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8761/actuator/health"]
      interval: 10s

  microservice-config-service:
    build: ./config-service
    container_name: microservice-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    depends_on:
       microservice-discovery-server:
         condition: service_healthy
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:9999/actuator/health" ]
      interval: 10s

  microservice-customer-service:
    build: ./customer-service
    container_name: microservice-customer-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    depends_on:
      microservice-discovery-server:
        condition: service_healthy
      microservice-config-service:
        condition: service_healthy
    healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
        interval: 10s
  microservice-account-service:
    build: ./account-service
    container_name: microservice-account-service
    ports:
        - '8082:8082'
    expose:
        - '8082'
    depends_on:
      microservice-discovery-server:
        condition: service_healthy
      microservice-config-service:
        condition: service_healthy
      microservice-customer-service:
        condition: service_healthy

  microservice-gateway-service:
    build: ./api-gateway
    container_name: microservice-gateway-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    depends_on:
      microservice-discovery-server:
        condition: service_healthy
      microservice-config-service:
        condition: service_healthy