server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8084/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: http://localhost:8081/
          predicates:
            - Path=/first/**
        - id: fraud
          uri: http://localhost:8082/
          predicates:
            - Path=/second/*